/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class kz_zhami_interview_jni_AwesomeLib */

#ifndef _Included_kz_zhami_interview_jni_AwesomeLib
#define _Included_kz_zhami_interview_jni_AwesomeLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     kz_zhami_interview_jni_AwesomeLib
 * Method:    helloHabr
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_kz_zhami_interview_jni_AwesomeLib_helloHabr
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
